-- 025: prescribed_medications_log — append-only feed of every signed
-- prescription entry, used as the data source for the future medication
-- learning loop (recommendations by diagnosis, brand-vs-generic preference
-- patterns, per-specialty norms, off-protocol anomaly detection).
-- See PHASE_2_BACKLOG.md "Medication learning loop" for the product
-- rationale and intended downstream uses.
--
-- Internal-only. This table is never read or filtered from a patient or
-- doctor view; it exists for product/ML offline analysis.
--
-- Schema notes:
--
--   * id / prescription_id / doctor_id are TEXT to match the existing
--     prescriptions / users tables (see 001_initial_tables.sql). UUIDs are
--     generated by the route via randomUUID() — same pattern as
--     prescriptions.id.
--
--   * created_at uses TIMESTAMP DEFAULT NOW() to match the convention in
--     001_initial_tables.sql (no TZ tracking on this log).
--
--   * medication_name_raw is the literal string the doctor typed — no
--     normalization at write time. Brand-vs-generic deduping, fuzzy
--     matching, and dictionary alignment all happen at read time when
--     the data feeds the ML pipeline. That keeps the write path cheap
--     and preserves the original signal.
--
--   * specialty is denormalized at write time (vs joining
--     users → specialties on read) so each log row stands alone if the
--     doctor's specialty is later changed or the user record deleted.
--
--   * ON DELETE CASCADE on prescription_id keeps the log consistent with
--     prescriptions: a prescription deleted → its log rows go too.
--
-- Indexes target the three most likely analytical filter axes:
--   - specialty (per-specialty pattern mining)
--   - doctor_id (per-doctor prescribing profile)
--   - created_at (time-windowed cohorts)

CREATE TABLE IF NOT EXISTS prescribed_medications_log (
  id                  TEXT PRIMARY KEY,
  prescription_id     TEXT NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
  doctor_id           TEXT NOT NULL,
  case_id             TEXT,
  diagnosis_text      TEXT,
  specialty           TEXT,
  medication_name_raw TEXT NOT NULL,
  dosage              TEXT,
  frequency           TEXT,
  duration            TEXT,
  instructions        TEXT,
  created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pml_specialty ON prescribed_medications_log(specialty);
CREATE INDEX IF NOT EXISTS idx_pml_doctor    ON prescribed_medications_log(doctor_id);
CREATE INDEX IF NOT EXISTS idx_pml_created   ON prescribed_medications_log(created_at);
