-- 028: refunds table — append-only ledger of patient refunds.
--
-- Per docs/PAYOUT_AND_URGENCY_POLICY.md §4 + §9.3, every patient refund
-- (SLA breach, doctor cancellation, platform error, etc.) writes one
-- row here. The Paymob actual-money refund is wired separately on
-- Ziad's track; for now this table records the intent + amount and the
-- earnings recalc hooks read from it.
--
-- Schema choices:
--   - id is TEXT to match the existing project convention (orders.id,
--     prescriptions.id, etc. are all TEXT-keyed UUIDs generated by the
--     route via randomUUID()).
--   - amount_egp is NUMERIC(10,2) so cents are preserved cleanly.
--   - reason is open TEXT (no CHECK) — common values: 'sla_breach',
--     'doctor_cancellation', 'platform_error'. Constraint added later
--     once the set stabilises.
--   - paymob_refund_id is nullable: populated when the Paymob refund
--     succeeds (Ziad's track), null while only the local intent exists.
--   - ON DELETE CASCADE on orders(id) keeps the ledger consistent if
--     an order is purged.
--
-- Idempotent — IF NOT EXISTS on the table + indexes.

BEGIN;

CREATE TABLE IF NOT EXISTS refunds (
  id                  TEXT PRIMARY KEY,
  order_id            TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  amount_egp          NUMERIC(10,2) NOT NULL,
  reason              TEXT NOT NULL,
  refunded_at         TIMESTAMP DEFAULT NOW(),
  refunded_by         TEXT,
  paymob_refund_id    TEXT,
  notes               TEXT
);

CREATE INDEX IF NOT EXISTS idx_refunds_order   ON refunds(order_id);
CREATE INDEX IF NOT EXISTS idx_refunds_reason  ON refunds(reason);
CREATE INDEX IF NOT EXISTS idx_refunds_created ON refunds(refunded_at);

COMMIT;
